### ISSUE TITLE
[🐛 Bug Report]: Cold Water Ritual Bug

### ISSUE THREAD

**Issue by MarkL-0** [FoonieMagus/ApeironBattleDemo_IssueList#115]
### Demo Environment

Production

### Battle Demo Version

v.0.5.170

### System Environment

OS: Win11

### What is expected?

Cold Water Ritual to stay in the play area after it was casted.

### What is happening?

It's going out then it'll come back for the explosion only. Could be visual bug but it's hard to identify if the skill is casted or not.

### Reproducible Bugs

stun or push the avatar after the skill was casted and it will disappear.

### Related link

https://drive.google.com/file/d/1MHbTd84hRJHbrBwIN7pqLK87U6JS98dz/view?usp=sharing

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/FoonieMagus/ApeironBattleDemo_IssueList/issues?q=label%3Abug) to ensure this bug has not already been reported

### No personal information provided

- [X] I confirm that I have not provided any personal information such as my wallet address or email address in this contribution.

### Open ticket if needed

- [X] In the event that personal information is required, I understand that I am expected to open a ticket in the [Discord](https://discord.gg/apeiron-doodaria) channel and reference the specific issue on Github.

**Comment by tanbod** [comment]
i dont know if this is intentional or not since by logic it make sense that if it interrupt skill should not be cast out
but for a skill that activate later 6 sec later for full damage with a 2 sec of cast time it too easy to interrupt 
like fighting wind avatar with AC1 AC2 they can chain stun and WC4 cannot cast any thing at all
either it back to old self it need to lower cast time significantly 
here video of current WC4
https://drive.google.com/file/d/1rSrfqPBFmnFJbXy9a3uBwx-pNFANLodj/view?usp=drive_link
this is a very big change it should be mention in patch note

**Comment by tanbod** [comment]
https://drive.google.com/file/d/1OIhqC8ssbNY-MF4TGNtKL0ir3EEf1eZe/view?usp=drive_link
clear video of this matter
